// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP2.Models.Data;

#nullable disable

namespace TP2.Migrations
{
    [DbContext(typeof(TPDbContext))]
    [Migration("20230824171645_AjoutData")]
    partial class AjoutData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TP2.Models.Enfant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenreDeFilm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdParent")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Vus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdParent");

                    b.ToTable("Enfants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = 2023,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 1,
                            ImageURL = "/Image/MOVIES_nouveau1.png",
                            Nom = "Spider Man",
                            Vus = 1000
                        },
                        new
                        {
                            Id = 2,
                            Date = 2023,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 1,
                            ImageURL = "/Image/MOVIES_nouveau2.png",
                            Nom = "About my father",
                            Vus = 2000
                        },
                        new
                        {
                            Id = 3,
                            Date = 2023,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 1,
                            ImageURL = "/Image/MOVIES_nouveau3.png",
                            Nom = "Blue Reette",
                            Vus = 3000
                        },
                        new
                        {
                            Id = 4,
                            Date = 2023,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 1,
                            ImageURL = "/Image/MOVIES_nouveau4.png",
                            Nom = "Annihilation",
                            Vus = 4000
                        },
                        new
                        {
                            Id = 5,
                            Date = 2022,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 2,
                            ImageURL = "/Image/MOVIES_avenir1.png",
                            Nom = "World Collide",
                            Vus = 5000
                        },
                        new
                        {
                            Id = 6,
                            Date = 2022,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 2,
                            ImageURL = "/Image/MOVIES_avenir2.png",
                            Nom = "World Collide 2",
                            Vus = 6000
                        },
                        new
                        {
                            Id = 7,
                            Date = 2022,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 2,
                            ImageURL = "/Image/MOVIES_avenir3.png",
                            Nom = "Mutant Mayhem",
                            Vus = 7000
                        },
                        new
                        {
                            Id = 8,
                            Date = 2022,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 2,
                            ImageURL = "/Image/MOVIES_avenir4.png",
                            Nom = "Titanic",
                            Vus = 8000
                        },
                        new
                        {
                            Id = 9,
                            Date = 2021,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 3,
                            ImageURL = "/Image/MOVIES_lesplusvus1.png",
                            Nom = "Inception",
                            Vus = 9000
                        },
                        new
                        {
                            Id = 10,
                            Date = 2021,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 3,
                            ImageURL = "/Image/MOVIES_lesplusvus2.png",
                            Nom = "Batman Begins",
                            Vus = 10000
                        },
                        new
                        {
                            Id = 11,
                            Date = 2021,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 3,
                            ImageURL = "/Image/MOVIES_lesplusvus3.png",
                            Nom = "Die hard",
                            Vus = 11000
                        },
                        new
                        {
                            Id = 12,
                            Date = 2021,
                            Description = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en pagele texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page est achevée. Généralement, on utilise un texte en faux latin, le Lorem ipsum ou Lipsum.",
                            GenreDeFilm = "Action",
                            IdParent = 3,
                            ImageURL = "/Image/MOVIES_lesplusvus4.png",
                            Nom = "Cold Souls",
                            Vus = 12000
                        });
                });

            modelBuilder.Entity("TP2.Models.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Le loremuite de mots sans  utilisée à titre provisoire pour calibrer une mise en page le texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page.",
                            ImageURL = "/Image/parent top.jpeg",
                            Nom = "NOUVEAUX"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Le loremuite de mots sans  utilisée à titre provisoire pour calibrer une mise en page le texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page.",
                            ImageURL = "/Image/parent-is comming.jpeg",
                            Nom = "À VENIR"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Le loremuite de mots sans  utilisée à titre provisoire pour calibrer une mise en page le texte définitif venant remplacer le faux-texte dès qu'il est prêt ou que la mise en page.",
                            ImageURL = "/Image/parent plus vus.jpeg",
                            Nom = "LES PLUS VUS"
                        });
                });

            modelBuilder.Entity("TP2.Models.Enfant", b =>
                {
                    b.HasOne("TP2.Models.Parent", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("IdParent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TP2.Models.Parent", b =>
                {
                    b.Navigation("Enfants");
                });
#pragma warning restore 612, 618
        }
    }
}
